### ISSUE TITLE
install docs: schema.sql

### ISSUE THREAD

**Issue by waldenn** [staart/api#1143]
Hi, I'm in the process to install / evaluate staart on my own server. Following the use-template-install-process I found these issues regarding the installing the DB schema:

* [This page](https://staart.js.org/api/getting-started.html) says: " Set up your database structure by running the contents of the schema.sql file in your SQL client and enter the database credentials in your .env file."
* And [this page](https://github.com/staart/api) says: Create MariaDB/MySQL tables based on schema.sql https://github.com/staart/api/blob/master/schema.sql (this link is dead!)

I see there is: https://github.com/staart/api/blob/master/prisma/schema.prisma
However I don't see docs for using Prisma for setting up the schema. I will read some docs on Prisma, but thought this was worth an issue.

Thanks for your work on this SaaS template!

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue! The docs are super incomplete and I'll make sure I update the getting starting guide soon. For now, this is what you should do:

1. Create the `.env` with required environment variables
2. In the `./prisma/` folder, create another `.env` file with only the `DATABASE_URL`: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/prisma-schema-file#defining-environment-variables-with-the-env-function

This should be enough to set up the database connection.

**Comment by waldenn** [comment]
Ok, thanks for the quick response.

I created a .env file: 

datasource mysql {
  provider = "mysql"
  url      = "mysql://root:mypass@localhost:3306/staart"
}

With permissions:

$ ls -l prisma/.env 
-rw-rw-rw- 1 jama jama 100 May 12 12:38 prisma/.env

Then proceeded to the build (I assumed I don't need to run any prisma CLI tool beforehand):

```
$ yarn build
yarn run v1.21.1
warning ../../package.json: License should be a valid SPDX license expression
$ staart build
cp: copyFileSync: could not write to dest file (code=ENOENT):.staart/prisma/.env
✔  success   Added middleware to controllers
✔  success   Generated paths
✔  success   Processed no redirect rules
✔  success   Setup 3 cron jobs
✔  success   Serving 2 static files
✔  success   Generated app.ts file
☐  pending   Compiling TypeScript
.staart/src/_staart/helpers/middleware.ts(128,21): error TS2339: Property 'startsWith' does not exist on type 'string | string[] | ParsedQs | ParsedQs[]'.
  Property 'startsWith' does not exist on type 'string[]'.
.staart/src/_staart/helpers/middleware.ts(129,31): error TS2339: Property 'replace' does not exist on type 'string | string[] | ParsedQs | ParsedQs[]'.
  Property 'replace' does not exist on type 'string[]'.
.staart/src/_staart/helpers/middleware.ts(131,9): error TS2345: Argument of type 'string | string[] | ParsedQs | ParsedQs[]' is not assignable to parameter of type 'string'.
  Type 'string[]' is not assignable to type 'string'.
.staart/src/_staart/helpers/middleware.ts(134,35): error TS2345: Argument of type 'string | string[] | ParsedQs | ParsedQs[]' is not assignable to parameter of type 'string'.
  Type 'string[]' is not assignable to type 'string'.
.staart/src/_staart/helpers/middleware.ts(183,57): error TS2345: Argument of type 'string | string[] | ParsedQs | ParsedQs[]' is not assignable to parameter of type 'string'.
  Type 'string[]' is not assignable to type 'string'.
.staart/src/_staart/helpers/middleware.ts(205,57): error TS2345: Argument of type 'string | string[] | ParsedQs | ParsedQs[]' is not assignable to parameter of type 'string'.
  Type 'string[]' is not assignable to type 'string'.
.staart/src/_staart/helpers/utils.ts(182,11): error TS2322: Type 'ParsedQs' is not assignable to type '{ [index: string]: string | string[]; }'.
  Index signatures are incompatible.
    Type 'string | string[] | ParsedQs | ParsedQs[]' is not assignable to type 'string | string[]'.
      Type 'ParsedQs' is not assignable to type 'string | string[]'.
        Type 'ParsedQs' is not assignable to type 'string'.
.staart/src/controllers/auth/oauth.ts(29,35): error TS2345: Argument of type '(error: Error) => void' is not assignable to parameter of type 'NextFunction'.
  Types of parameters 'error' and 'deferToNext' are incompatible.
    Type '"router"' is not assignable to type 'Error'.
.staart/src/controllers/auth/oauth.ts(73,50): error TS2345: Argument of type 'ParsedQs' is not assignable to parameter of type 'ParsedUrlQueryInput'.
  Index signatures are incompatible.
    Type 'string | string[] | ParsedQs | ParsedQs[]' is not assignable to type 'string | number | boolean | string[] | number[] | boolean[] | null | undefined'.
      Type 'ParsedQs' is not assignable to type 'string | number | boolean | string[] | number[] | boolean[] | null | undefined'.
        Type 'ParsedQs' is not assignable to type 'string'.
.staart/src/controllers/auth/oauth.ts(91,50): error TS2345: Argument of type 'ParsedQs' is not assignable to parameter of type 'ParsedUrlQueryInput'.
.staart/src/controllers/auth/oauth.ts(109,50): error TS2345: Argument of type 'ParsedQs' is not assignable to parameter of type 'ParsedUrlQueryInput'.
.staart/src/controllers/auth/oauth.ts(127,50): error TS2345: Argument of type 'ParsedQs' is not assignable to parameter of type 'ParsedUrlQueryInput'.
.staart/src/controllers/auth/oauth.ts(145,50): error TS2345: Argument of type 'ParsedQs' is not assignable to parameter of type 'ParsedUrlQueryInput'.
Done in 29.64s.
```

So the build fails.

Running the server then also fails ofcourse: node dist/src/index.js

```
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module '/home/jama/dev/conzept-backend/dist/src/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

```

Thanks again.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
This is fixed in v3. We now use Prisma and therefore support all `prisma migrate` and `prisma db` commands for installation and migration.
