### ISSUE TITLE
The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined

### ISSUE THREAD

**Issue by imshashank** [staart/api#1424]
Issues with a fresh install

```
✖  error     Database connection: Test failed
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined
    at prepareSecretKey (internal/crypto/keys.js:324:11)
    at new Hmac (internal/crypto/hash.js:111:9)
    at Object.createHmac (crypto.js:143:10)
    at Object.exports.sign (/Users/shashank/Projects/PipfeedWorkspace/web/api/node_modules/twt/dist/index.js:25:91)
    at /Users/shashank/Projects/PipfeedWorkspace/web/api/dist/src/_staart/helpers/prisma.js:65:41
    at Array.forEach (<anonymous>)
    at /Users/shashank/Projects/PipfeedWorkspace/web/api/dist/src/_staart/helpers/prisma.js:62:33
    at Array.map (<anonymous>)
    at /Users/shashank/Projects/PipfeedWorkspace/web/api/dist/src/_staart/helpers/prisma.js:61:16
    at Generator.next (<anonymous>) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I think the problem is with not being able to find "config("twtSecret")"

Not sure what this means.

I just installed the API & UI. Used the Ui to try to create a user and then this was the error returned each time.

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @imshashank!

Can you please try setting the environment variable `TWT_SECRET = "secret"`?

**Comment by AnandChowdhary** [comment]
This is now fixed in v3. If you didn't set up an environment variable for TWT secret, it defaults to an empty string.
